//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOpsFlex.DSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "flex";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DevOpsFlex";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Skills Funding Agency";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DevOpsFlexDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DevOpsFlexCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DevOpsFlexExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DevOpsFlexCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDevOpsFlexExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DevOpsFlexCommandSetId), 0x0001);
	
		// Package identifier
		public const string DevOpsFlexPackageId = "9d96a236-19aa-425c-b3ac-027b81a83df6";
		
		// Editor factory identifier
		public const string DevOpsFlexEditorFactoryId = "9cc103fc-44f8-46b8-b35d-44ea5f7e51dc";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DevOpsFlexModelExplorerToolWindowId = "447efe86-60c9-423e-8815-7c596db3b46e";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace DevOpsFlex.DSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DevOpsFlexCommandSetId = "f6ebcef0-71f8-4208-a55a-c6294b6a51a1";
	}
}