//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using global::System.Linq;

namespace DevOpsFlex.DSL
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class DevOpsFlexDocData : DevOpsFlexDocDataBase
	{
		/// <summary>
		/// Constructs a new DevOpsFlexDocData.
		/// </summary>
		public DevOpsFlexDocData(global::System.IServiceProvider serviceProvider, global::System.Guid editorFactoryId) 
			: base(serviceProvider, editorFactoryId)
		{
		}
	}

	/// <summary>
	/// Class which represents a DevOpsFlex document in memory.
	/// </summary>
	internal abstract partial class DevOpsFlexDocDataBase : DslShell::ModelingDocData
	{
		/// <summary>
		/// Document lock holder registered for the subordinate .diagram file.
		/// </summary>
		protected DslShell::SubordinateDocumentLockHolder diagramDocumentLockHolder;

		/// <summary>
		/// Constructs a new DevOpsFlexDocDataBase.
		/// </summary>
		protected DevOpsFlexDocDataBase(global::System.IServiceProvider serviceProvider, global::System.Guid editorFactoryId) : base(serviceProvider, editorFactoryId)
		{
		}

		/// <summary>
		/// Returns a list of file format specifiers for the Save dialog box.
		/// </summary>
		protected override string FormatList
		{
			get
			{
				return global::DevOpsFlex.DSL.DevOpsFlexDomainModel.SingletonResourceManager.GetString("FormatList"); 
			}
		}

		#region Composition container

		/// <summary>
		/// Create and return a new store
		/// </summary>
		/// <remarks>
		/// Override the default behaviour to put the doc data's composition container into the store's property bag.
		/// By default, the runtime will add the CompositionService from the DslShell ModelingCompositionContainer
		/// if the property has not already been set.
		/// </remarks>
		protected override DslModeling::Store CreateStore()
		{
			DslModeling::Store store = base.CreateStore();

			global::System.ComponentModel.Composition.ICompositionService compositionService = this.CompositionService;
			// Add the composition container to the property bag even if it is null. This will prevent the runtime from
			// adding the shared ModelingCompositionContainer.CompositionService.
			store.PropertyBag.Add(DslModeling::ExtensionEnablement.ExtensionEnablementConstants.ContainerId, compositionService);

			return store;
		}

		/// <summary>
		/// Initialize the doc data
		/// </summary>
		public override void Initialize(DslModeling::Store sharedStore)
		{
			this.InitializeComposition();
			base.Initialize(sharedStore);
		}
				
		/// <summary>
		/// The MEF composition container used by the doc data.
		/// </summary>
		/// <remarks>Can be null. Returns the shared modeling composition service by default.</remarks>
		protected virtual global::System.ComponentModel.Composition.ICompositionService CompositionService
		{
			get
			{
				return DslShell::ModelingCompositionContainer.CompositionService;
			}
		}

		/// <summary>
		/// The MEF Export Provider used by the doc data.
		/// </summary>
		/// <remarks>Can be null. Returns the shared modeling export provider by default</remarks>
		protected virtual global::System.ComponentModel.Composition.Hosting.ExportProvider ExportProvider
		{
			get
			{
				return DslShell::ModelingCompositionContainer.ExportProvider;
			}		
		}

		/// <summary>
		/// Satisfy Imports in DocData object
		/// </summary>		
		protected virtual void InitializeComposition()
		{
			global::System.ComponentModel.Composition.ICompositionService compositionService = this.CompositionService;
			if (compositionService != null)
			{		
				try
				{
					compositionService.SatisfyImportsOnce(global::System.ComponentModel.Composition.AttributedModelServices.CreatePart(this));
				}
				catch (global::System.Exception ex)
				{
					// Handle binding failures
					if (!HandleBindingFailure(ex))
					{
						throw;
					}
				}
			}
		}

		/// <summary>
		/// Handles exceptions that occurred during binding.
		/// </summary>
		/// <param name="exception">The exception that occured</param>
		/// <returns>A flag indicating whether the exception was handled or not.</returns>
		/// <remarks>If the exception is not handled (i.e. the method returns false), it will be re-thrown
		/// by the calling method.
		/// This method will be called for all types of exception.</remarks>
		protected virtual bool HandleBindingFailure(global::System.Exception exception)
		{
			// Log and suppress all binding failure exceptions.
			string errorMessage = string.Format(global::System.Globalization.CultureInfo.CurrentCulture,
				global::DevOpsFlex.DSL.DevOpsFlexDomainModel.SingletonResourceManager.GetString("BindingErrorOccurred"),
				exception.ToString());
			
			this.AddErrorListItem(new DslShell::SimpleErrorListItem(errorMessage, this.FileName, global::Microsoft.VisualStudio.Shell.TaskPriority.Normal, global::Microsoft.VisualStudio.Shell.TaskErrorCategory.Warning));
			return true;
		}

		#endregion // CompositionContainer

		#region SerializerLocator

		/// <summary>
		/// Resolves the xml namespaces to domain model types
		/// </summary>
		private DslModeling::ISerializerLocator serializerLocator;

		/// <summary>
		/// The domain model resolver used during serialization.
		/// </summary>
		protected DslModeling::ISerializerLocator SerializerLocator
		{
			get
			{
				if (this.serializerLocator == null)
				{
					this.serializerLocator = CreateSerializerLocator();
				}
				return this.serializerLocator;
			}
		}

		/// <summary>
		/// Factory method to create a SerializerLocator.
		/// </summary>
		protected virtual DslModeling::ISerializerLocator CreateSerializerLocator()
		{
			// If we don't have a MEF ExportProvider, we won't be able to resolve
			// any namespaces.
			if (this.ExportProvider == null)
			{
				return null;
			}

			return new DslModeling::StandardSerializerLocator(this.ExportProvider);
		}

		#endregion // SerializerLocator
		
		#region ExtensionLocator

		/// <summary>
		/// Used to locate domain model extensions
		/// </summary>
		private DslModeling::IExtensionLocator extensionLocator;

		/// <summary>
		/// The locator used to find domain model extensions.
		/// </summary>
		protected DslModeling::IExtensionLocator ExtensionLocator
		{
			get
			{
				if (this.extensionLocator == null)
				{
					this.extensionLocator = CreateExtensionLocator();
				}
				return this.extensionLocator;
			}
		}

		/// <summary>
		/// Factory method to create an ExtensionLocator.
		/// </summary>
		protected virtual DslModeling::IExtensionLocator CreateExtensionLocator()
		{
			// If we don't have an MEF ExportProvider, we won't be able to locate
			// any extensions
			if (this.ExportProvider == null)
			{
				return null;
			}

			return new DslModeling::StandardExtensionLocator(this.ExportProvider);
		}

		#endregion // ExtensionLocator


		/// <summary>
		/// When the doc data is closed, make sure we reset the valiation messages 
		/// (if there's any) from the ErrorList window.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (this.diagramDocumentLockHolder != null)
				{
					this.diagramDocumentLockHolder.Dispose();
					this.diagramDocumentLockHolder = null;
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		/// <summary>
		/// Returns a collection of domain models to load into the store.
		/// </summary>
		/// <remarks>The default implementation includes any extension domain models returned by the call to GetExtensionDomainModels().</remarks>
		protected override global::System.Collections.Generic.IList<global::System.Type> GetDomainModels()
		{
			global::System.Collections.Generic.List<global::System.Type> allTypes = new System.Collections.Generic.List<System.Type>();

			// In the type of our base domain model
			allTypes.Add(typeof(global::DevOpsFlex.DSL.DevOpsFlexDomainModel));

			// Add in any extension domain models
			global::System.Collections.Generic.IEnumerable<global::System.Type> extensionTypes = this.GetExtensionDomainModels();
			if (extensionTypes != null && extensionTypes.Count() > 0)
			{
				allTypes.AddRange(extensionTypes);
			}

			return allTypes;
		}

		/// <summary>
		/// Returns the list of extension domain models to be loaded
		/// </summary>
		/// <returns>A list of domain model types. Can be empty.</returns>
		/// <remarks>This method is called by "GetDomainModels", which aggregates the returned lists.</remarks>
		protected virtual global::System.Collections.Generic.IEnumerable<global::System.Type> GetExtensionDomainModels()
		{
			if (this.ExtensionLocator == null)
			{
				return null;
			}

			global::System.Collections.Generic.IEnumerable<global::System.Type> extensionDomainModels = this.ExtensionLocator.GetExtendingDomainModels(typeof(global::DevOpsFlex.DSL.DevOpsFlexDomainModel));

			return extensionDomainModels;
		}




		/// <summary>
		/// Loads the given file.
		/// </summary>
		protected override void Load(string fileName, bool isReload)
		{
			DslModeling::SerializationResult serializationResult = new DslModeling::SerializationResult();
			global::DevOpsFlex.DSL.DevOpsSystem modelRoot = null;
			DslModeling::ISchemaResolver schemaResolver = new DslShell::ModelingSchemaResolver(this.ServiceProvider);
			//clear the current root element
			this.SetRootElement(null);
			modelRoot = global::DevOpsFlex.DSL.DevOpsFlexSerializationHelper.Instance.LoadModel(serializationResult, this.GetModelPartition(), fileName, schemaResolver, null /* no load-time validation */, this.SerializerLocator);

			// Report serialization messages.
			this.SuspendErrorListRefresh();
			try
			{
				foreach (DslModeling::SerializationMessage serializationMessage in serializationResult)
				{
					this.AddErrorListItem(new DslShell::SerializationErrorListItem(this.ServiceProvider, serializationMessage));
				}
			}
			finally
			{
				this.ResumeErrorListRefresh();
			}

			if (serializationResult.Failed)
			{	
				// Load failed, can't open the file.
				throw new global::System.InvalidOperationException(global::DevOpsFlex.DSL.DevOpsFlexDomainModel.SingletonResourceManager.GetString("CannotOpenDocument"));
			}
			else
			{
				this.SetRootElement(modelRoot);
				
				// Attempt to set the encoding
				if (serializationResult.Encoding != null)
				{
					this.ModelingDocStore.SetEncoding(serializationResult.Encoding);
					global::Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(this.SetDocDataDirty(0)); // Setting the encoding will mark the document as dirty, so clear the dirty flag.
				}
				
			}
		}


		/// <summary>
		/// Saves the given file.
		/// </summary>
		protected override void Save(string fileName)
		{
			DslModeling::SerializationResult serializationResult = new DslModeling::SerializationResult();
			global::DevOpsFlex.DSL.DevOpsSystem modelRoot = (global::DevOpsFlex.DSL.DevOpsSystem)this.RootElement;

			global::DevOpsFlex.DSL.DevOpsFlexSerializationHelper.Instance.SaveModel(serializationResult, modelRoot, fileName, this.Encoding, false);
			// Report serialization messages.
			this.SuspendErrorListRefresh();
			try
			{
				foreach (DslModeling::SerializationMessage serializationMessage in serializationResult)
				{
					this.AddErrorListItem(new DslShell::SerializationErrorListItem(this.ServiceProvider, serializationMessage));
				}
			}
			finally
			{
				this.ResumeErrorListRefresh();
			}

			if (serializationResult.Failed)
			{	// Save failed.
				throw new global::System.InvalidOperationException(global::DevOpsFlex.DSL.DevOpsFlexDomainModel.SingletonResourceManager.GetString("CannotSaveDocument"));
			}
		}
		
		#region Base virtual overrides
		
		/// <summary>
		/// Return the model in XML format
		/// </summary>
		protected override string SerializedModel
		{
			get
			{
				global::DevOpsFlex.DSL.DevOpsSystem modelRoot = this.RootElement as global::DevOpsFlex.DSL.DevOpsSystem;
				string modelFile = string.Empty;
				if (modelRoot != null)
				{
					modelFile = global::DevOpsFlex.DSL.DevOpsFlexSerializationHelper.Instance.GetSerializedModelString(modelRoot, this.Encoding);
				}
				return modelFile;
			}
		}
		#endregion

		#region Partition Support
		/// <summary>
		/// Get the Partition where model data will be loaded into.
		/// Base implementation returns the default partition of the store.
		/// </summary>
		protected internal virtual DslModeling::Partition GetModelPartition()
		{
			if (this.Store != null)
			{
				return this.Store.DefaultPartition;
			}
			
			return null;
		}
		#endregion
	}
}
